// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_name_ from "./routes/api/[name].tsx";
import * as $api_book_chapters from "./routes/api/book/chapters.ts";
import * as $api_book_content from "./routes/api/book/content.ts";
import * as $api_book_info from "./routes/api/book/info.ts";
import * as $api_login_check from "./routes/api/login/check.ts";
import * as $api_login_sse from "./routes/api/login/sse.ts";
import * as $api_shelf from "./routes/api/shelf.ts";
import * as $api_tts_index from "./routes/api/tts/index.ts";
import * as $api_tts_openxing_voices from "./routes/api/tts/openxing-voices.ts";
import * as $api_tts_openxing from "./routes/api/tts/openxing.ts";
import * as $api_tts_voices from "./routes/api/tts/voices.ts";
import * as $book_id_ from "./routes/book/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $reader_bookId_chapterUid_ from "./routes/reader/[bookId]/[chapterUid].tsx";
import * as $shelf from "./routes/shelf.tsx";
import * as $BookDetailComponent from "./islands/BookDetailComponent.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $HomeComponent from "./islands/HomeComponent.tsx";
import * as $LoginComponent from "./islands/LoginComponent.tsx";
import * as $ReaderComponent from "./islands/ReaderComponent.tsx";
import * as $ShelfComponent from "./islands/ShelfComponent.tsx";
import * as $WeReadStyleReaderComponent from "./islands/WeReadStyleReaderComponent.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/[name].tsx": $api_name_,
    "./routes/api/book/chapters.ts": $api_book_chapters,
    "./routes/api/book/content.ts": $api_book_content,
    "./routes/api/book/info.ts": $api_book_info,
    "./routes/api/login/check.ts": $api_login_check,
    "./routes/api/login/sse.ts": $api_login_sse,
    "./routes/api/shelf.ts": $api_shelf,
    "./routes/api/tts/index.ts": $api_tts_index,
    "./routes/api/tts/openxing-voices.ts": $api_tts_openxing_voices,
    "./routes/api/tts/openxing.ts": $api_tts_openxing,
    "./routes/api/tts/voices.ts": $api_tts_voices,
    "./routes/book/[id].tsx": $book_id_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/reader/[bookId]/[chapterUid].tsx": $reader_bookId_chapterUid_,
    "./routes/shelf.tsx": $shelf,
  },
  islands: {
    "./islands/BookDetailComponent.tsx": $BookDetailComponent,
    "./islands/Counter.tsx": $Counter,
    "./islands/HomeComponent.tsx": $HomeComponent,
    "./islands/LoginComponent.tsx": $LoginComponent,
    "./islands/ReaderComponent.tsx": $ReaderComponent,
    "./islands/ShelfComponent.tsx": $ShelfComponent,
    "./islands/WeReadStyleReaderComponent.tsx": $WeReadStyleReaderComponent,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
